### ISSUE TITLE
Update to support Wynntils v1.1.0

### ISSUE THREAD

**Issue by ForgotMyPasswd** [aws404/ControlifyWynn#1]
[Wynntils](https://github.com/Wynntils/Artemis/releases/tag/v1.1.0) was recently updated to v1.1.0, which breaks ControlifyWynn compatibility with the mod and prevents Wynntils from working in game.

**Comment by aws404** [comment]
Yep, will work on restoring compatibility next week. You will temporarily have to remove the mod to use Wynntils.
